import { expect, test } from '@playwright/test'

test('раздел протоколов открывает создание и архив', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Войти' }).click()
  await expect(page.getByText('ДНК реестр', { exact: true })).toBeVisible()

  await page.getByRole('button', { name: 'Протоколы' }).click()
  await page.getByRole('button', { name: 'Создать', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Создать протокол' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Выделение', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Real Time', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'PCR', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Форез', exact: true })).toBeVisible()
  await expect(page.getByText('Выберите объекты, чтобы построить плашку.')).toBeVisible()
  await expect(page.getByPlaceholder('№ рег РЦСМЭ от')).toBeVisible()
  await expect(page.getByPlaceholder('№ рег РЦСМЭ до')).toBeVisible()
  await expect(page.getByLabel('Описание')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Вставить список номеров' })).toBeEnabled()
  await expect(page.getByPlaceholder('Тип объекта')).toHaveCount(0)
  await expect(page.getByPlaceholder('Коробка')).toHaveCount(0)

  await page.getByRole('button', { name: 'Вставить список номеров' }).click()
  await page.getByPlaceholder('7600-1\n7601-1\n7602-1').fill('999999999-999')
  await page.getByRole('button', { name: 'Применить' }).click()
  await expect(page.getByText('Найдено: 0 из 1')).toBeVisible()
  await expect(page.getByPlaceholder('№ рег РЦСМЭ от')).toHaveCount(0)
  await expect(page.getByLabel('Описание')).toBeEnabled()
  await page.getByRole('button', { name: /Очистить список/ }).click()
  await expect(page.getByPlaceholder('№ рег РЦСМЭ от')).toBeVisible()

  await page.getByRole('button', { name: 'Партии протокола' }).click()
  await page.locator('.multi-party-modal input[type="checkbox"]').first().check()
  await page.getByRole('button', { name: 'Готово' }).click()
  await expect(page.getByRole('button', { name: /1 партий · \d+ объектов/ })).toBeVisible()
  await expect(page.locator('.protocol-selection-actions strong')).not.toHaveText('Выбрано: 0')
  const pcrRecalculated = page.waitForResponse((response) => response.url().includes('/protocols/preview') && response.request().method() === 'POST')
  await page.locator('.protocol-stage').nth(2).getByLabel('Набор').selectOption({ index: 1 })
  await pcrRecalculated
  const forezRecalculated = page.waitForResponse((response) => response.url().includes('/protocols/preview') && response.request().method() === 'POST')
  await page.locator('.protocol-stage').nth(3).getByLabel('Набор').selectOption({ index: 1 })
  await forezRecalculated
  await expect(page.getByRole('button', { name: 'Предпросмотр печати' })).toBeEnabled()
  await page.getByRole('button', { name: 'Предпросмотр печати' }).click()
  await page.getByRole('button', { name: 'Предпросмотр', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Разведения', exact: true }).first()).toBeVisible()
  await expect(page.locator('.protocol-print-page').getByText('Протокол PCR', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Закрыть' }).click()

  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: 'Сохранённые' }).click()
  await expect(page.getByRole('heading', { name: 'Сохранённые протоколы' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Сегодня' })).toBeVisible()
  await expect(page.getByText('Дополнительные фильтры')).toBeVisible()
})
